# From services
- com.restaurantrant.entity.Account
- com.restaurantrant.entity.SleepRecord
- com.restaurantrant.entity.FoodRecord
- com.restaurantrant.entity.ExerciseRecord
- com.restaurantrant.entity.Recipe
- com.restaurantrant.entity.Exercise
- com.restaurantrant.entity.HashKey

