# From services
- com.health.entity.Account
- com.health.entity.SleepRecord
- com.health.entity.FoodRecord
- com.health.entity.ExerciseRecord
- com.health.entity.Recipe
- com.health.entity.Exercise
- com.health.entity.HashKey

