# From services
- com.restaurant.entity.InventoryItem
- com.restaurant.entity.MenuInventoryItem
- com.restaurant.entity.MenuItem
- com.restaurant.entity.Order
- com.restaurant.entity.OrderItem
- com.restaurant.entity.Payment
- com.restaurant.entity.PaymentMethod
- com.restaurant.entity.PurchaseOrder
- com.restaurant.entity.PurchaseOrderItem
- com.restaurant.entity.Refund
- com.restaurant.entity.Role
- com.restaurant.entity.User

